name: Benchmark

on: [push]

jobs:
  build:
    name: Benchmark Rust code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bench

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
      - name: Run benchmarks
        run: ./bench.sh pollard_rho_1
