name: Pylint

on: [push]

jobs:
  build:
    name: Run pylint on Python scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        python-script:
          - apc.run/submit.py
          - atcoder/ranking.py
          - cafecoder/submit.py
          - yukicoder/remaining.py
          - yukicoder/submit.py
          - yukicoder/upload.py
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint -r yukicoder/requirements.txt -r apc.run/requirements.txt
    - name: Analyze the code with pylint
      run: |
        pylint ${{ matrix.python-script }} --fail-under=9
